package com.haulmont.testtask.view.design.abstraction;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class PatientFormDesign extends VerticalLayout {
    protected Grid<com.haulmont.testtask.model.Patient> grid;
    protected Button back;
    protected Button add;
    protected Button update;
    protected Button delete;

    public PatientFormDesign() {
        Design.read(this);
    }
}
